Repository Outer-Wilds-New-Horizons/new-horizons, pull requests merged in 2022-10, with the labels that each got.

#399 1.6.1
  NewHorizons/Assets/addon-manifest.json
  NewHorizons/Builder/Props/DetailBuilder.cs
  NewHorizons/Builder/Props/NomaiTextBuilder.cs
  NewHorizons/Builder/Props/RemoteBuilder.cs
  NewHorizons/Builder/Props/ScatterBuilder.cs
  NewHorizons/Builder/ShipLog/RumorModeBuilder.cs
  NewHorizons/Builder/Volumes/AudioVolumeBuilder.cs
  NewHorizons/External/Modules/PropModule.cs
  NewHorizons/External/Modules/VolumesModule.cs
  NewHorizons/Main.cs
  NewHorizons/Schemas/body_schema.json
  NewHorizons/Utility/DebugUtilities/DebugRaycaster.cs
  NewHorizons/Utility/NewHorizonBody.cs
  NewHorizons/Utility/SearchUtilities.cs
  NewHorizons/manifest.json
Labels: update-pr

#406 Translate credits, popups, update OWML version
  NewHorizons/Main.cs
  NewHorizons/NewHorizons.csproj
  NewHorizons/manifest.json
Labels: update-pr

#412 v1.6.3
  NewHorizons/Builder/General/RFVolumeBuilder.cs
  NewHorizons/Builder/General/SectorBuilder.cs
  NewHorizons/Builder/Props/DetailBuilder.cs
  NewHorizons/Builder/Props/NomaiTextBuilder.cs
  NewHorizons/Builder/Props/SignalBuilder.cs
  NewHorizons/Builder/ShipLog/RumorModeBuilder.cs
  NewHorizons/Builder/Volumes/AudioVolumeBuilder.cs
  NewHorizons/Components/ShipLog/ShipLogStarChartMode.cs
  NewHorizons/External/Configs/PlanetConfig.cs
  NewHorizons/Handlers/AudioTypeHandler.cs
  NewHorizons/Handlers/RemoteHandler.cs
  NewHorizons/Handlers/StarChartHandler.cs
  NewHorizons/Main.cs
  NewHorizons/NewHorizons.csproj
  NewHorizons/OtherMods/CustomShipLogModes/CustomShipLogModesHandler.cs
  NewHorizons/OtherMods/CustomShipLogModes/ICustomShipLogModes.cs
  NewHorizons/Patches/AudioSignalPatches.cs
  NewHorizons/Patches/WarpDrivePatches.cs
  NewHorizons/Schemas/body_schema.json
  NewHorizons/Utility/AudioUtilities.cs
  NewHorizons/Utility/EnumUtilities.cs
  NewHorizons/Utility/NewHorizonExtensions.cs
  NewHorizons/manifest.json
Labels: update-pr

#414 1.6.4
  NewHorizons/Builder/General/RFVolumeBuilder.cs
  NewHorizons/manifest.json
Labels: update-pr

#432 1.7.1
  NewHorizons/Builder/Props/DetailBuilder.cs
  NewHorizons/Patches/ShipLogPatches.cs
  NewHorizons/manifest.json
Labels: update-pr

#434 docs: add cli tool section
  docs/content/pages/tutorials/translation.md
Labels: documentation

#427 Add Generic API Methods
  NewHorizons/INewHorizons.cs
  NewHorizons/NewHorizonsApi.cs
  docs/content/pages/tutorials/api.md
  docs/content/pages/tutorials/extending.md
Labels: feature
