Repository Outer-Wilds-New-Horizons/new-horizons, pull requests merged in 2022-08, with the labels that each got.

#257 Fix bramble exits
  NewHorizons/Builder/Body/BrambleDimensionBuilder.cs
  NewHorizons/Builder/Props/BrambleNodeBuilder.cs
Labels: bug

#264 Fix default tornado type
  NewHorizons/External/Modules/PropModule.cs
  NewHorizons/Schemas/body_schema.json
Labels: bug

#309 1.5.1
  NewHorizons/Builder/Props/ProjectionBuilder.cs
  NewHorizons/Components/SizeControllers/StarEvolutionController.cs
  NewHorizons/NewHorizons.csproj
  NewHorizons/manifest.json
  SchemaExporter/SchemaExporter.csproj
Labels: update-pr

#324 Make rain/snow heights more robust
  NewHorizons/Builder/Atmosphere/EffectsBuilder.cs
Labels: bug

#320 Add Support For Extra Modules
  NewHorizons/External/Configs/PlanetConfig.cs
  NewHorizons/External/Configs/StarSystemConfig.cs
  NewHorizons/Handlers/PlanetCreationHandler.cs
  NewHorizons/INewHorizons.cs
  NewHorizons/Main.cs
  NewHorizons/NewHorizonsApi.cs
  NewHorizons/Schemas/body_schema.json
  NewHorizons/Schemas/star_system_schema.json
  NewHorizons/Utility/NewHorizonsSystem.cs
  SchemaExporter/SchemaExporter.cs
  docs/content/pages/tutorials/api.md
  docs/content/pages/tutorials/extending.md
Labels: feature, nice to have
