Repository Outer-Wilds-New-Horizons/new-horizons, pull requests merged in 2022-09, with the labels that each got.

#338 Transparent clouds
  NewHorizons/Assets/xen.newhorizons
  NewHorizons/Assets/xen.newhorizons.manifest
  NewHorizons/Builder/Atmosphere/AtmosphereBuilder.cs
  NewHorizons/Builder/Atmosphere/CloudsBuilder.cs
  NewHorizons/Builder/Atmosphere/EffectsBuilder.cs
  NewHorizons/Builder/Body/ProxyBuilder.cs
  NewHorizons/Components/TransparentCloudRenderQueueController.cs
  NewHorizons/External/Modules/AtmosphereModule.cs
  NewHorizons/Handlers/PlanetCreationHandler.cs
  NewHorizons/Handlers/TitleSceneHandler.cs
  NewHorizons/Schemas/body_schema.json
Labels: feature

#356 Rewrite Docs
  docs/content/pages/editor.md
  docs/content/pages/home.md
  docs/content/pages/tutorials/api.md
  docs/content/pages/tutorials/creating_addon.md
  docs/content/pages/tutorials/details.md
  docs/content/pages/tutorials/dialogue.md
  docs/content/pages/tutorials/extending.md
  docs/content/pages/tutorials/getting_started.md
  docs/content/pages/tutorials/planet_gen.md
  docs/content/pages/tutorials/publishing.md
  docs/content/pages/tutorials/reading_schemas.md
  docs/content/pages/tutorials/ship_log.md
  docs/content/pages/tutorials/star_system.md
  docs/content/pages/tutorials/translation.md
  docs/content/pages/tutorials/update_existing.md
  docs/content/pages/tutorials/xml.md
  docs/content/static/images/editor/log_port.webp
  docs/content/static/images/getting_started/mod_manager_show_in_explorer.webp
  docs/content/static/images/home/create_planets.webp
  docs/content/static/images/home/mod_manager_dots.webp
  docs/content/static/images/planet_gen/earth_heightmap.webp
  docs/content/static/images/reading_schemas/body_schema_1.webp
  docs/content/static/images/reading_schemas/body_schema_2.webp
  docs/content/static/images/reading_schemas/body_schema_3.webp
  docs/content/static/images/reading_schemas/body_schema_4.webp
  docs/content/static/images/reading_schemas/body_schema_5.webp
Labels: documentation

#380 fix credits (from eye pr lol)
  NewHorizons/Handlers/CreditsHandler.cs
Labels: priority

#377 Allow overriding far clip plane
  NewHorizons/External/Configs/StarSystemConfig.cs
  NewHorizons/Patches/MapControllerPatches.cs
  NewHorizons/Patches/OWCameraPatch.cs
  NewHorizons/Schemas/star_system_schema.json
Labels: priority

#339 Scatter optimization
  NewHorizons/Builder/Props/DetailBuilder.cs
  NewHorizons/Builder/Props/ScatterBuilder.cs
  NewHorizons/External/Modules/PropModule.cs
  NewHorizons/OtherMods/MenuFramework/MenuHandler.cs
  NewHorizons/Schemas/body_schema.json
Labels: priority

#345 Disable starlights when out of range
  NewHorizons/Builder/Body/StarBuilder.cs
  NewHorizons/Components/SizeControllers/StarEvolutionController.cs
  NewHorizons/Components/StarLightController.cs
  NewHorizons/Handlers/PlanetCreationHandler.cs
  NewHorizons/Handlers/PlanetDestructionHandler.cs
Labels: priority
